-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "totalSale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalStock" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ProductDetail" ADD COLUMN     "sale" INTEGER NOT NULL DEFAULT 0;
